import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { getFirestore, doc, setDoc, getDoc, collection, addDoc, getDocs, deleteDoc, serverTimestamp, query, orderBy } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyCemBB24eO8qEDqt-AcK-2WqqdLGxUeHM",authDomain:"restaurant-saas-c894e.firebaseapp.com",projectId:"restaurant-saas-c894e",storageBucket:"restaurant-saas-c894e.firebasestorage.app",messagingSenderId:"857683742785",appId:"1:857683742785:web:6eaa2b6f9fa598ba1736c0",measurementId:"G-JBLCYSKHNS"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let currentUser=null,currentTenant=null;
window.show=(id)=>{document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='dashboard')loadDashboard()}
function msg(t){document.getElementById('authMsg').textContent=t}
window.register=async()=>{try{let name=restaurantName.value.trim(),email=emailInput().value.trim(),pass=password.value;if(!name||!email||!pass)return msg('اكتب اسم المطعم والإيميل وكلمة المرور');let res=await createUserWithEmailAndPassword(auth,email,pass);await setDoc(doc(db,'tenants',res.user.uid),{restaurantName:name,email,plan:'Free',createdAt:serverTimestamp()});msg('تم إنشاء الحساب بنجاح');show('dashboard')}catch(e){msg('خطأ: '+e.message)}}
function emailInput(){return document.getElementById('email')}
window.login=async()=>{try{await signInWithEmailAndPassword(auth,emailInput().value.trim(),password.value);msg('تم تسجيل الدخول');show('dashboard')}catch(e){msg('خطأ: '+e.message)}}
window.logout=async()=>{await signOut(auth);show('home')}
onAuthStateChanged(auth,async(user)=>{currentUser=user;document.getElementById('logoutBtn').classList.toggle('hide',!user);document.getElementById('authBtn').classList.toggle('hide',!!user);if(user){let snap=await getDoc(doc(db,'tenants',user.uid));currentTenant=snap.exists()?snap.data():null;loadDashboard()}});
async function loadDashboard(){if(!currentUser){notLogged.classList.remove('hide');dashContent.classList.add('hide');return}notLogged.classList.add('hide');dashContent.classList.remove('hide');rName.textContent=currentTenant?.restaurantName||'مطعمي';rEmail.textContent=currentUser.email;await loadMenu();await loadOrders()}
window.addItem=async()=>{if(!currentUser)return show('auth');let name=itemName.value.trim(),price=Number(itemPrice.value),category=itemCategory.value.trim()||'عام';if(!name||!price)return alert('اكتب اسم الصنف والسعر');await addDoc(collection(db,'tenants',currentUser.uid,'menu'),{name,price,category,createdAt:serverTimestamp()});itemName.value=itemPrice.value=itemCategory.value='';loadMenu()}
async function loadMenu(){if(!currentUser)return;let q=query(collection(db,'tenants',currentUser.uid,'menu'),orderBy('createdAt','desc'));let snap=await getDocs(q);menuCount.textContent=snap.size;menuList.innerHTML='';snap.forEach(d=>{let x=d.data();menuList.innerHTML+=`<div class="item"><b>${x.name}</b><br>${x.category} - ${x.price} جنيه <button class="danger" onclick="deleteItem('${d.id}')">حذف</button></div>`})}
window.deleteItem=async(id)=>{await deleteDoc(doc(db,'tenants',currentUser.uid,'menu',id));loadMenu()}
window.addOrder=async()=>{if(!currentUser)return show('auth');let customer=customerName.value.trim(),phone=customerPhone.value.trim();if(!customer)return alert('اكتب اسم العميل');await addDoc(collection(db,'tenants',currentUser.uid,'orders'),{customer,phone,status:'new',total:0,createdAt:serverTimestamp()});customerName.value=customerPhone.value='';loadOrders()}
async function loadOrders(){if(!currentUser)return;let q=query(collection(db,'tenants',currentUser.uid,'orders'),orderBy('createdAt','desc'));let snap=await getDocs(q);ordersCount.textContent=snap.size;ordersList.innerHTML='';snap.forEach(d=>{let x=d.data();ordersList.innerHTML+=`<div class="item"><b>${x.customer}</b><br>${x.phone||''}<br>الحالة: ${x.status}</div>`})}
